m1 = float(input('Digite a primeira nota:'))
m2 = float(input('Digite a segunda nota:'))
m3 = float(input('Digite a terceira nota:'))
m4 = float(input('Digite a quarta nota.'))
soma = float(m1 + m2 + m3 + m4)
div = float(soma / 4)
print('A sua média é {}'.format(div))
