numero = float(input('Digite um numero:'))
dobro = float(numero * 2)
triplo = float(numero * 3)
raiz = float(numero **(1/2))
print('O dobro é {}, seu triplo é {}, a raiz quadrada é {:.2f}.'.format(dobro, triplo, raiz))
