num = int(input('Digite o numero qual deseja saber a tabuada:'))
n1 = int(num * 1)
n2 = int(num * 2)
n3 = int(num * 3)
n4 = int(num * 4)
n5 = int(num * 5)
n6 = int(num * 6)
n7 = int(num * 7)
n8 = int(num * 8)
n9 = int(num * 9)
n10 = int(num * 10)
print('========>TABUADA<========')
print(' {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n {} \n'.format(n1, n2, n3, n4, n5, n6, n7, n8, n9, n10))
